In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[2,3,4],[3,4,9]])

In [3]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 9]])

In [6]:
np.ndim(a)

2

In [7]:
np.shape(a)

(3, 3)

In [8]:
np.linalg.matrix_rank(a)

3

In [9]:
b = np.array([[[1,2,3,4],[1,3,4,5]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])

In [10]:
b

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 7, 5],
        [8, 4, 3, 5]],

       [[2, 5, 7, 3],
        [1, 5, 3, 7]]])

In [12]:
s=np.shape(b)

In [13]:
s

(3, 2, 4)

In [19]:
rank=len(s)

In [25]:
b[1][1][3]

5

In [26]:
item = np.array([[1,4,8],[2,3,5],[2,5,1],[1,10,7]])

In [27]:
item

array([[ 1,  4,  8],
       [ 2,  3,  5],
       [ 2,  5,  1],
       [ 1, 10,  7]])

In [28]:
item.sum(axis = 1)

array([13, 10,  8, 18])

In [29]:
item.sum(axis = 0)

array([ 6, 22, 21])

In [31]:
b.sum()

94

In [32]:
b.sum(axis = 0)

array([[ 5, 11, 17, 12],
       [10, 12, 10, 17]])

In [33]:
b.sum(axis = 1)

array([[ 2,  5,  7,  9],
       [10,  8, 10, 10],
       [ 3, 10, 10, 10]])

In [35]:
b.sum(axis = 2)

array([[10, 13],
       [18, 20],
       [17, 16]])

In [36]:
np.sort(b)

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 5, 7],
        [3, 4, 5, 8]],

       [[2, 3, 5, 7],
        [1, 3, 5, 7]]])

In [37]:
b

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 7, 5],
        [8, 4, 3, 5]],

       [[2, 5, 7, 3],
        [1, 5, 3, 7]]])

In [39]:
np.sort(b, axis = 0)

array([[[1, 2, 3, 3],
        [1, 3, 3, 5]],

       [[2, 4, 7, 4],
        [1, 4, 3, 5]],

       [[2, 5, 7, 5],
        [8, 5, 4, 7]]])

In [40]:
np.sort(b, axis = 1)

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 3, 5],
        [8, 4, 7, 5]],

       [[1, 5, 3, 3],
        [2, 5, 7, 7]]])

In [41]:
np.sort(b, axis = 2)

array([[[1, 2, 3, 4],
        [1, 3, 4, 5]],

       [[2, 4, 5, 7],
        [3, 4, 5, 8]],

       [[2, 3, 5, 7],
        [1, 3, 5, 7]]])

In [42]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.random.random(3)

array([0.91636643, 0.1878038 , 0.55775456])

In [45]:
data=np.array([1,2])
ones=np.ones(2)

In [46]:
data+ones

array([2., 3.])

In [47]:
data - ones

array([0., 1.])

In [48]:
data * data

array([1, 4])

In [49]:
data / data

array([1., 1.])

In [50]:
data * 1.6

array([1.6, 3.2])

In [52]:
d=np.array([1,2,3])

In [53]:
d[1:]

array([2, 3])

In [54]:
d.min()

1

In [55]:
d.max()

3

In [56]:
d.sum()

6

In [57]:
d.mean()

2.0

In [58]:
d.prod()

6

In [59]:
d.std()

0.816496580927726

In [60]:
Z = np.zeros((10,10))

In [62]:
Z.size

100

In [64]:
Z.itemsize

8

In [ ]:
np.info(np.add)

In [67]:
z=np.arange(10,50)

In [68]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [69]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int32),)

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
Z = np.random.random((10,10))

In [73]:
Z

array([[0.93322973, 0.78075507, 0.09632498, 0.18649405, 0.12040223,
        0.62130756, 0.49017879, 0.54886249, 0.05477004, 0.94848742],
       [0.25867145, 0.70840288, 0.68765677, 0.45799479, 0.56203956,
        0.18413852, 0.89494488, 0.03843053, 0.61473691, 0.38040894],
       [0.1346809 , 0.75686909, 0.3098955 , 0.02418608, 0.19602444,
        0.57653192, 0.20102283, 0.0026617 , 0.71143906, 0.1064044 ],
       [0.02415372, 0.98875528, 0.17194155, 0.37689004, 0.80032341,
        0.10830757, 0.08578173, 0.57899672, 0.51882454, 0.45175901],
       [0.87451475, 0.38970817, 0.34063533, 0.12182607, 0.64929918,
        0.35592792, 0.2653904 , 0.60952454, 0.30427077, 0.64535354],
       [0.51013368, 0.73162827, 0.99230649, 0.00839991, 0.75723427,
        0.17989163, 0.96894684, 0.86545884, 0.09273938, 0.17156113],
       [0.77738949, 0.82170676, 0.17480668, 0.27001763, 0.86066899,
        0.18328637, 0.16441097, 0.37500734, 0.0949155 , 0.79200757],
       [0.64392329, 0.51294322, 0.8443734

In [74]:
Zmin, Zmax = Z.min(), Z.max()

In [75]:
Zmin

0.002661704071380555

In [76]:
Zmax

0.9923064931859095

In [77]:
Z.mean()

0.44672064277798074

In [79]:
Z=np.ones((10,10))

In [80]:
Z[1:-1,1:-1]=0

In [81]:
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [82]:
Z=np.ones((5,5))

In [83]:
np.pad(Z, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [84]:
0*np.nan

nan

In [85]:
np.nan==np.nan

False

In [86]:
np.inf>np.nan

False

In [87]:
np.nan-np.nan

nan

In [88]:
0.3==3*0.1

False

In [89]:
 np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [90]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])

In [91]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [92]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [104]:
Z = np.arange(11)

In [105]:
Z[3:8] *= -1

In [106]:
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

In [3]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr = np.arange(10)

In [8]:
arr[arr % 2 == 1]=-1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
arr.reshape(2, -1)  

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [11]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.concatenate([a, b], axis=0) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.concatenate([a, b], axis=1) 

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [21]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
a = np.array([1,2,3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

In [32]:
np.intersect1d(a,b) 

array([2, 4])

In [33]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [35]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int32),)

In [36]:
a = np.arange(15)

In [37]:
index = np.where((a >= 5) & (a <= 10)) 

In [39]:
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
index = np.where(np.logical_and(a>=5, a<=10)) 

In [42]:
index

(array([ 5,  6,  7,  8,  9, 10], dtype=int32),)

In [43]:
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])


In [46]:
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [47]:
arr = np.arange(9).reshape(3,3) 

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [50]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [51]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [52]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [53]:
np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3)) 

array([[8.40811038, 6.02232562, 6.73415921],
       [7.25485539, 6.44277012, 5.44470912],
       [5.32172896, 5.40466721, 6.41462193],
       [8.17704304, 5.48515635, 9.30204622],
       [8.71801924, 9.77530461, 6.24017386]])

In [54]:
rand_arr = np.random.uniform(5,10, size=(5,3)) 

In [55]:
rand_arr = np.random.random([5,3]) 

# 答案：
# 设置保留 3 位小数 
np.set_printoptions(precision=3) 

In [56]:
rand_arr

array([[0.824, 0.233, 0.218],
       [0.954, 0.815, 0.521],
       [0.015, 0.123, 0.072],
       [0.918, 0.403, 0.026],
       [0.02 , 0.545, 0.858]])

In [57]:
np.set_printoptions(suppress=True, precision=6)  # precision 是可选项

In [71]:
rand_arr

array([[0.823569, 0.232927, 0.217652],
       [0.95428 , 0.814699, 0.521349],
       [0.015025, 0.122989, 0.072382],
       [0.91818 , 0.402786, 0.026282],
       [0.019736, 0.544916, 0.857649]])

In [86]:
np.set_printoptions(threshold=none) 

NameError: name 'none' is not defined

In [85]:
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 
iris = np.genfromtxt(url, delimiter=',', dtype='object') 
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')  
# 输出前三行 
iris[:3] 

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [4]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])  

# 答案 
Smax, Smin = sepallength.max(), sepallength.min() 
S = (sepallength - Smin)/(Smax - Smin) 
#

In [8]:
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [9]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [11]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3]) 
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan  


print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum()) 
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0]))) 

Number of missing values: 
 4
Position of missing values: 
 (array([ 2,  7, 31, 33], dtype=int32),)


In [12]:
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [0. , 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [13]:
species = np.array([row.tolist()[4] for row in iris]) 
np.unique(species, return_counts=True) 

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))

In [14]:
iris[iris[:,0].argsort()][:5]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa']], dtype=object)

In [15]:
vals, counts = np.unique(iris[:, 2], return_counts=True)

In [16]:
vals[np.argmax(counts)]

b'1.5'